vich_uploader:
    db_driver: orm

    mappings:
        posts:
            uri_prefix: /uploads/images/posts
            upload_destination: '%kernel.project_dir%/uploads/images/posts'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
